# Generated by Django 4.2.7 on 2025-07-30 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bmr', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_metrics_summary', models.BooleanField(default=True)),
                ('show_recent_activities', models.BooleanField(default=True)),
                ('show_pending_tasks', models.BooleanField(default=True)),
                ('show_notifications', models.BooleanField(default=True)),
                ('auto_refresh_enabled', models.BooleanField(default=True)),
                ('refresh_interval_seconds', models.IntegerField(default=30)),
                ('layout_config', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('phase_assigned', 'Phase Assigned'), ('phase_completed', 'Phase Completed'), ('phase_rejected', 'Phase Rejected'), ('bmr_approved', 'BMR Approved'), ('quality_alert', 'Quality Alert'), ('deadline_approaching', 'Deadline Approaching'), ('system_maintenance', 'System Maintenance')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmr.bmr')),
                ('phase_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.batchphaseexecution')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('active_batches', models.IntegerField(default=0)),
                ('completed_phases_today', models.IntegerField(default=0)),
                ('pending_phases', models.IntegerField(default=0)),
                ('rejected_phases_today', models.IntegerField(default=0)),
                ('role_specific_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
