# Generated by Django 4.2.7 on 2025-07-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
    ]
