# Generated by Django 4.2.7 on 2025-07-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_usersession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('qa', 'Quality Assurance'), ('regulatory', 'Regulatory'), ('store_manager', 'Store Manager'), ('mixing_operator', 'Mixing Operator'), ('qc', 'Quality Control'), ('tube_filling_operator', 'Tube Filling Operator'), ('packaging_store', 'Packaging Store'), ('packing_supervisor', 'Packing Supervisor'), ('granulation_operator', 'Granulation Operator'), ('blending_operator', 'Blending Operator'), ('compression_operator', 'Compression Operator'), ('sorting_operator', 'Sorting Operator'), ('coating_operator', 'Coating Operator'), ('drying_operator', 'Drying Operator'), ('filling_operator', 'Filling Operator'), ('blister_packing_operator', 'Blister Packing Operator'), ('bulk_packing_operator', 'Bulk Packing Operator'), ('packing_operator', 'Packing Operator'), ('capsule_filling_operator', 'Capsule Filling Operator'), ('tablet_coating_operator', 'Tablet Coating Operator'), ('weighing_operator', 'Weighing Operator'), ('dispensing_operator', 'Dispensing Operator'), ('batch_production_operator', 'Batch Production Operator'), ('line_clearance_operator', 'Line Clearance Operator'), ('equipment_operator', 'Equipment Operator'), ('cleaning_operator', 'Cleaning Operator'), ('validation_officer', 'Validation Officer'), ('production_supervisor', 'Production Supervisor'), ('shift_supervisor', 'Shift Supervisor')], max_length=30),
        ),
    ]
