# Generated by Django 4.2.7 on 2025-07-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('qa', 'Quality Assurance'), ('regulatory', 'Regulatory'), ('store_manager', 'Store Manager'), ('packaging_store', 'Packaging Store'), ('finished_goods_store', 'Finished Goods Store'), ('qc', 'Quality Control'), ('mixing_operator', 'Mixing Operator'), ('tube_filling_operator', 'Tube Filling Operator'), ('granulation_operator', 'Granulation Operator'), ('blending_operator', 'Blending Operator'), ('compression_operator', 'Compression Operator'), ('coating_operator', 'Coating Operator'), ('drying_operator', 'Drying Operator'), ('filling_operator', 'Filling Operator'), ('sorting_operator', 'Sorting Operator'), ('packing_operator', 'Packing Operator'), ('dispensing_operator', 'Dispensing Operator'), ('equipment_operator', 'Equipment Operator'), ('cleaning_operator', 'Cleaning Operator')], max_length=30),
        ),
    ]
