# Generated by Django 5.2.5 on 2025-08-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bmr', '0003_rawmaterialrelease_remove_bmr_batch_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, unique=True)),
                ('material_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('active', 'Active Pharmaceutical Ingredient'), ('excipient', 'Excipient'), ('packaging', 'Packaging Material'), ('other', 'Other')], max_length=20)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=4, max_digits=10)),
                ('default_supplier', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensing_reference', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Dispensing'), ('in_progress', 'Dispensing In Progress'), ('completed', 'Dispensing Complete'), ('cancelled', 'Dispensing Cancelled')], default='pending', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('dispensing_notes', models.TextField(blank=True)),
                ('bmr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_dispensing', to='bmr.bmr')),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=4, max_digits=10)),
                ('supplier', models.CharField(max_length=200)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('pending_qc', 'Pending QC'), ('approved', 'QC Approved'), ('rejected', 'QC Rejected'), ('expired', 'Expired'), ('depleted', 'Depleted')], default='pending_qc', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='raw_materials.rawmaterial')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_raw_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDispensingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dispensed_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('bmr_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_items', to='bmr.bmrmaterial')),
                ('dispensing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='raw_materials.materialdispensing')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_usages', to='raw_materials.rawmaterialbatch')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('appearance_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('identification_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('assay_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True)),
                ('purity_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True)),
                ('final_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_raw_material_qc', to=settings.AUTH_USER_MODEL)),
                ('material_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_test', to='raw_materials.rawmaterialbatch')),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_qc_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
