# Generated by Django 4.2.7 on 2025-08-21 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialqc',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_raw_material_qc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialqc',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialqc',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_raw_material_qc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialqc',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialqc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rawmaterialqc',
            name='test_notes',
            field=models.TextField(blank=True),
        ),
    ]
