# Generated by Django 4.2.7 on 2025-09-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_materials', '0002_rawmaterialqc_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_raw_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_raw_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
