# Generated by Django 5.2.6 on 2025-09-11 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0007_bmrmaterial_material'),
        ('raw_materials', '0005_rawmaterialbatch_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialqc',
            name='loss_on_drying',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage loss on drying test', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialqc',
            name='ph_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='pH value measurement', max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('received', 'Material Received'), ('dispensed', 'Material Dispensed'), ('returned', 'Material Returned'), ('adjusted', 'Quantity Adjusted'), ('expired', 'Material Expired'), ('rejected', 'Material Rejected')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='raw_materials.rawmaterialbatch')),
                ('reference_bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='bmr.bmr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
