# Generated by Django 4.2.7 on 2025-07-30 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bmr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPhaseExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('phase_data', models.JSONField(blank=True, default=dict)),
                ('operator_comments', models.TextField(blank=True)),
                ('qa_comments', models.TextField(blank=True)),
                ('qc_approved', models.BooleanField(blank=True, null=True)),
                ('qc_approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('bmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_executions', to='bmr.bmr')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_phases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bmr', 'phase__phase_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('ointment', 'Ointment'), ('tablet_normal', 'Tablet Normal'), ('tablet_2', 'Tablet 2'), ('capsule', 'Capsule')], max_length=20)),
                ('phase_name', models.CharField(choices=[('bmr_creation', 'BMR Creation'), ('regulatory_approval', 'Regulatory Approval'), ('material_dispensing', 'Material Dispensing'), ('quality_control', 'Quality Control'), ('packaging_material_release', 'Packaging Material Release'), ('secondary_packaging', 'Secondary Packaging'), ('final_qa', 'Final QA'), ('finished_goods_store', 'Finished Goods Store'), ('mixing', 'Mixing'), ('tube_filling', 'Tube Filling'), ('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('sorting', 'Sorting'), ('coating', 'Coating'), ('blister_packing', 'Blister Packing'), ('bulk_packing', 'Bulk Packing'), ('drying', 'Drying'), ('filling', 'Filling')], max_length=30)),
                ('phase_order', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('can_rollback_to', models.ForeignKey(blank=True, help_text='Phase to rollback to if this phase fails', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.productionphase')),
            ],
            options={
                'ordering': ['product_type', 'phase_order'],
                'unique_together': {('product_type', 'phase_name')},
            },
        ),
        migrations.CreateModel(
            name='PhaseCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_name', models.CharField(max_length=200)),
                ('expected_value', models.CharField(max_length=200)),
                ('actual_value', models.CharField(blank=True, max_length=200)),
                ('is_within_spec', models.BooleanField(blank=True, null=True)),
                ('checked_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phase_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='workflow.batchphaseexecution')),
            ],
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.productionphase'),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='qc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_approved_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhaseOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_operator', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.productionphase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phase')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='batchphaseexecution',
            unique_together={('bmr', 'phase')},
        ),
    ]
