# Generated by Django 4.2.7 on 2025-07-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_productionphase_phase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20),
        ),
    ]
