# Generated by Django 4.2.7 on 2025-08-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_fix_tablet_2_workflow_permanent'),
        ('workflow', '0004_alter_batchphaseexecution_status'),
    ]

    operations = [
    ]
