# Generated by Django 4.2.7 on 2025-08-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_fix_tablet_2_phase_order'),
        ('workflow', '0005_merge_20250806_1643'),
    ]

    operations = [
    ]
