# Generated by Django 4.2.7 on 2025-08-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_fix_tablet_2_phase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchphaseexecution',
            name='breakdown_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='breakdown_occurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='breakdown_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='changeover_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='changeover_occurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='changeover_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('coating', 'Coating'), ('blister_packing', 'Blister Packing'), ('filling', 'Filling')], max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Active machines are available for selection')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['machine_type', 'name'],
                'unique_together': {('name', 'machine_type')},
            },
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='machine_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.machine'),
        ),
    ]
