# Generated by Django 4.2.7 on 2025-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_batchphaseexecution_breakdown_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchphaseexecution',
            name='breakdown_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='changeover_reason',
            field=models.TextField(blank=True),
        ),
    ]
