# Generated by Django 4.2.7 on 2025-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_batchphaseexecution_breakdown_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('coating', 'Coating'), ('blister_packing', 'Blister Packing'), ('bulk_packing', 'Bulk Packing'), ('filling', 'Filling')], max_length=20),
        ),
    ]
