# Generated by Django 4.2.7 on 2025-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_machine_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('coating', 'Coating'), ('blister_packing', 'Blister Packing'), ('bulk_packing', 'Bulk Packing'), ('filling', 'Filling'), ('mixing', 'Mixing'), ('tube_filling', 'Tube Filling'), ('drying', 'Drying'), ('sorting', 'Sorting')], max_length=20),
        ),
    ]
