# Generated by Django 4.2.7 on 2025-08-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bmr', '0002_alter_bmr_batch_number_alter_bmr_in_process_controls_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_remove_product_is_coated_product_coating_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGSInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(default='units', max_length=20)),
                ('storage_date', models.DateTimeField(auto_now_add=True)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('shelf_life_months', models.IntegerField(default=24)),
                ('expiry_date', models.DateField()),
                ('release_certificate_number', models.CharField(blank=True, max_length=50)),
                ('qa_approval_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('available', 'Available for Sale'), ('reserved', 'Reserved'), ('released', 'Released/Sold'), ('expired', 'Expired'), ('recalled', 'Recalled')], default='stored', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bmr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fgs_inventory', to='bmr.bmr')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('qa_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_approved_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FGS Inventory',
                'verbose_name_plural': 'FGS Inventory',
                'ordering': ['-storage_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_type', models.CharField(choices=[('sale', 'Sale'), ('transfer', 'Transfer'), ('donation', 'Donation'), ('destruction', 'Destruction'), ('return', 'Return')], default='sale', max_length=20)),
                ('quantity_released', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('release_reference', models.CharField(max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_contact', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_releases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='fgs_management.fgsinventory')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='FGSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expiry_warning', 'Expiry Warning'), ('low_stock', 'Low Stock'), ('quality_issue', 'Quality Issue'), ('system', 'System Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fgs_management.fgsinventory')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'priority'],
            },
        ),
    ]
