# Generated by Django 4.2.7 on 2025-08-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgs_management', '0002_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fgsinventory',
            options={'ordering': ['-created_at'], 'verbose_name': 'FGS Inventory', 'verbose_name_plural': 'FGS Inventory'},
        ),
        migrations.AlterField(
            model_name='fgsinventory',
            name='status',
            field=models.CharField(choices=[('stored', 'Stored'), ('available', 'Available for Sale'), ('reserved', 'Reserved'), ('released', 'Released/Sold'), ('recalled', 'Recalled')], default='stored', max_length=20),
        ),
    ]
