# Generated by Django 4.2.7 on 2025-08-18 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bmr', '0003_rawmaterialrelease_remove_bmr_batch_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title describing the defect', max_length=100)),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Detailed description of the defect')),
                ('image', models.ImageField(blank=True, null=True, upload_to='defect_reports/%Y/%m/%d/')),
                ('production_phase', models.CharField(help_text='Phase where defect was observed', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_required', 'Action Required'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the QA review')),
                ('corrective_action', models.TextField(blank=True, help_text='Actions taken to address the defect')),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='bmr.bmr')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_defects', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Defect Report',
                'verbose_name_plural': 'Defect Reports',
                'ordering': ['-reported_date'],
            },
        ),
    ]
