# Generated by Django 4.2.7 on 2025-07-30 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr_number', models.CharField(max_length=20, unique=True)),
                ('batch_number', models.CharField(max_length=10, unique=True)),
                ('batch_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_size_unit', models.CharField(default='units', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('planned_start_date', models.DateTimeField()),
                ('planned_completion_date', models.DateTimeField()),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('manufacturing_instructions', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('in_process_controls', models.TextField()),
                ('quality_checks_required', models.TextField()),
                ('qa_comments', models.TextField(blank=True)),
                ('regulatory_comments', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bmrs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bmrs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Batch Manufacturing Record',
                'verbose_name_plural': 'Batch Manufacturing Records',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BMRMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('material_code', models.CharField(max_length=50)),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('batch_lot_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('dispensed_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('bmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='bmr.bmr')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BMRSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('created', 'Created'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('dispensed', 'Materials Dispensed'), ('production_started', 'Production Started'), ('production_completed', 'Production Completed'), ('qc_approved', 'QC Approved'), ('final_approval', 'Final Approval')], max_length=30)),
                ('signed_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('bmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='bmr.bmr')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bmr', 'signature_type', 'signed_by')},
            },
        ),
    ]
