# Generated by Django 4.2.7 on 2025-07-30 13:25

import bmr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmr',
            name='batch_number',
            field=models.CharField(help_text='Enter batch number in format XXXYYYY (e.g., 0012025)', max_length=10, unique=True, validators=[bmr.models.validate_batch_number]),
        ),
        migrations.AlterField(
            model_name='bmr',
            name='in_process_controls',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bmr',
            name='manufacturing_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bmr',
            name='planned_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bmr',
            name='planned_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bmr',
            name='quality_checks_required',
            field=models.TextField(blank=True),
        ),
    ]
