# Generated by Django 4.2.7 on 2025-08-11 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmr', '0002_alter_bmr_batch_number_alter_bmr_in_process_controls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Release'), ('released', 'Released to Dispensing'), ('received', 'Received by Dispensing'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('release_started_date', models.DateTimeField(blank=True, null=True)),
                ('release_completed_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('release_comments', models.TextField(blank=True)),
                ('receiving_comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.RemoveField(
            model_name='bmr',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='bmr',
            name='batch_size_unit',
        ),
        migrations.AddField(
            model_name='bmr',
            name='actual_batch_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual batch size (if different from standard product batch size)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bmr',
            name='actual_batch_size_unit',
            field=models.CharField(blank=True, help_text='Unit for actual batch size (inherits from product if not specified)', max_length=20),
        ),
        migrations.CreateModel(
            name='RawMaterialReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('released_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('batch_lot_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmr.bmrmaterial')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bmr.rawmaterialrelease')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterialrelease',
            name='bmr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_releases', to='bmr.bmr'),
        ),
        migrations.AddField(
            model_name='rawmaterialrelease',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialrelease',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
