# Generated by Django 4.2.7 on 2025-09-03 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmr', '0003_rawmaterialrelease_remove_bmr_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='materials_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bmr',
            name='materials_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_approved_bmrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bmr',
            name='materials_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
