# Generated by Django 4.2.7 on 2025-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0004_bmr_materials_approved_bmr_materials_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='material_status',
            field=models.CharField(choices=[('pending', 'Pending Dispensing'), ('dispensing', 'Dispensing in Progress'), ('dispensed', 'Materials Dispensed'), ('returned', 'Materials Returned')], default='pending', max_length=20),
        ),
    ]
