# Generated by Django 4.2.7 on 2025-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0005_bmr_material_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for this batch', null=True),
        ),
        migrations.AddField(
            model_name='bmr',
            name='manufacture_date',
            field=models.DateField(blank=True, help_text='Date of manufacture for this batch', null=True),
        ),
    ]
