# Generated by Django 5.2.6 on 2025-09-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0006_bmr_expiry_date_bmr_manufacture_date'),
        ('raw_materials', '0005_rawmaterialbatch_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrmaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bmr_materials', to='raw_materials.rawmaterial'),
        ),
    ]
