# Generated by Django 4.2.7 on 2025-07-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('ointment', 'Ointment'), ('tablet_normal', 'Tablet Normal'), ('tablet_2', 'Tablet 2'), ('capsule', 'Capsule')], max_length=20)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('gel', 'Gel')], max_length=20)),
                ('strength', models.CharField(max_length=100)),
                ('pack_size', models.CharField(max_length=50)),
                ('is_coated', models.BooleanField(default=False, help_text='Only applicable for tablets')),
                ('tablet_subtype', models.CharField(blank=True, help_text='normal or 2', max_length=20)),
                ('manufacturing_method', models.TextField()),
                ('storage_conditions', models.CharField(max_length=200)),
                ('shelf_life_months', models.IntegerField()),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=200)),
                ('test_method', models.CharField(max_length=200)),
                ('acceptance_criteria', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('ingredient_type', models.CharField(choices=[('active', 'Active Ingredient'), ('inactive', 'Inactive Ingredient'), ('excipient', 'Excipient')], max_length=20)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product')),
            ],
        ),
    ]
