# Generated by Django 4.2.7 on 2025-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='dosage_form',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturing_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shelf_life_months',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_conditions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tablet_subtype',
        ),
        migrations.AddField(
            model_name='product',
            name='tablet_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Tablet'), ('tablet_2', 'Tablet Type 2')], help_text='Only applicable for tablets - normal or tablet type 2', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_coated',
            field=models.BooleanField(default=False, help_text='Only applicable for tablets - whether the tablet is coated or not'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ointment', 'Ointment'), ('tablet', 'Tablet'), ('capsule', 'Capsule')], max_length=20),
        ),
    ]
