# Generated by Django 4.2.7 on 2025-07-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_dosage_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_coated',
        ),
        migrations.AddField(
            model_name='product',
            name='coating_type',
            field=models.CharField(blank=True, choices=[('uncoated', 'Uncoated'), ('coated', 'Coated')], help_text='Only applicable for tablets - whether the tablet is coated or not', max_length=20),
        ),
    ]
