# Generated by Django 4.2.7 on 2025-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_coated_product_coating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_size_unit',
            field=models.CharField(default='units', help_text='Unit of measurement for batch size (units, kg, liters, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_batch_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowable batch size', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_batch_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowable batch size', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_batch_size',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Standard batch size for this product', max_digits=10),
        ),
    ]
