# Generated by Django 4.2.7 on 2025-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_batch_size_unit_product_maximum_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_size_in_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of individual packaging unit (e.g., tablets per blister, capsules per bottle, ml per tube)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='batch_size_unit',
            field=models.CharField(default='units', help_text='Unit of measurement for batch size (automatically set based on product type)', max_length=20),
        ),
    ]
