# Generated by Django 4.2.7 on 2025-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_packaging_size_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maximum_batch_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_batch_size',
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Capsule (Blister)'), ('bulk', 'Bulk Capsule')], default='normal', help_text='Only applicable for capsules - normal (blister) or bulk', max_length=20),
        ),
    ]
