# Generated by Django 4.2.7 on 2025-08-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_rawmaterialqc_completed_by_and_more'),
        ('products', '0006_remove_product_maximum_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='raw_materials.rawmaterial'),
        ),
    ]
