# Generated by Django 4.2.7 on 2025-09-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0005_rawmaterialbatch_approved_by_and_more'),
        ('products', '0007_product_raw_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('is_active_ingredient', models.BooleanField(default=False, help_text='Check if this is an active pharmaceutical ingredient')),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='products.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='raw_materials.rawmaterial')),
            ],
            options={
                'verbose_name': 'Product Material',
                'verbose_name_plural': 'Product Materials',
                'unique_together': {('product', 'raw_material')},
            },
        ),
    ]
