# Generated by Django 4.2.7 on 2025-09-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'ordering': ['product__product_name', 'is_active_ingredient'], 'verbose_name': 'Product Material', 'verbose_name_plural': 'Product Materials'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='raw_materials',
        ),
    ]
