# Generated by Django 4.2.7 on 2025-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),  # Make sure to adjust this if needed
        ('products', '0009_alter_productmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='raw_materials.rawmaterial'),
        ),
    ]
